-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 12:15:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dio` DEFAULT CHARACTER SET utf8 ;
USE `dio` ;

-- -----------------------------------------------------
-- Table `dio`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Tipo Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Tipo Serviço` (
  `idStatus` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL COMMENT 'Tipos: consertados ou revisões  periódicas',
  PRIMARY KEY (`idStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `Nome da equipe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEquipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Carro` (
  `idCarro` INT NOT NULL AUTO_INCREMENT,
  `Modelo` VARCHAR(45) NOT NULL,
  `Placa` VARCHAR(45) NOT NULL,
  `idCliente` INT NOT NULL,
  `idStatus` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idCarro`),
  INDEX `fk_Carro_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Carro_Tipo Serviço1_idx` (`idStatus` ASC) VISIBLE,
  INDEX `fk_Carro_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Carro_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_Tipo Serviço1`
    FOREIGN KEY (`idStatus`)
    REFERENCES `dio`.`Tipo Serviço` (`idStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carro_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `dio`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Mecanicos` (
  `idMecanicos` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idMecanicos`),
  INDEX `fk_Mecanicos_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Mecanicos_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `dio`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Especialidades` (
  `idEspecialidades` INT NOT NULL AUTO_INCREMENT,
  `Especialidade` VARCHAR(45) NOT NULL,
  `idMecanicos` INT NOT NULL,
  PRIMARY KEY (`idEspecialidades`),
  INDEX `fk_Especialidades_Mecanicos1_idx` (`idMecanicos` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidades_Mecanicos1`
    FOREIGN KEY (`idMecanicos`)
    REFERENCES `dio`.`Mecanicos` (`idMecanicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Status OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Status OS` (
  `idStatus OS` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idStatus OS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Autorização`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Autorização` (
  `idAutorização` INT NOT NULL AUTO_INCREMENT,
  `Status` VARCHAR(45) NOT NULL COMMENT 'Autorizado pelo cliente\nNão autorizado pelo cliente',
  PRIMARY KEY (`idAutorização`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`OS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`OS` (
  `idOS` INT NOT NULL AUTO_INCREMENT,
  `data de emissão` DATE NOT NULL,
  `data para conclusão` DATE NULL,
  `Valor Peças` FLOAT NULL,
  `idStatus OS` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  `idAutorização` INT NOT NULL,
  PRIMARY KEY (`idOS`),
  INDEX `fk_OS_Status OS1_idx` (`idStatus OS` ASC) VISIBLE,
  INDEX `fk_OS_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  INDEX `fk_OS_Autorização1_idx` (`idAutorização` ASC) VISIBLE,
  CONSTRAINT `fk_OS_Status OS1`
    FOREIGN KEY (`idStatus OS`)
    REFERENCES `dio`.`Status OS` (`idStatus OS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `dio`.`Equipe` (`idEquipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OS_Autorização1`
    FOREIGN KEY (`idAutorização`)
    REFERENCES `dio`.`Autorização` (`idAutorização`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dio`.`Serviços`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dio`.`Serviços` (
  `idServiços` INT NOT NULL AUTO_INCREMENT,
  `serviço` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `idOS` INT NOT NULL,
  PRIMARY KEY (`idServiços`),
  INDEX `fk_Serviços_OS1_idx` (`idOS` ASC) VISIBLE,
  CONSTRAINT `fk_Serviços_OS1`
    FOREIGN KEY (`idOS`)
    REFERENCES `dio`.`OS` (`idOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
